name: 'Skedulo Migration'
description: 'Skedulo Migration Actions'
inputs:
  SERVICES:
    description: 'Services to migrate: OrgPreference,JobTypes,JobTemplates,CustomFields,CustomForm,Package'
    required: true
  SOURCE_API_SERVER:
    description: 'Source API Server'
    required: true
  SOURCE_TOKEN:
    description: 'Source Token'
    required: true
  TARGET_API_SERVER:
    description: 'Target API Server'
    required: true
  TARGET_TOKEN:
    description: 'Target Token'
    required: true
runs:
  using: node16
  main: 'dist/index.js'