name: Skedulo Enviroment Migration

on:
  workflow_dispatch:
    inputs:
      SOURCE_API_SERVER:
        description: "Source API server"
        type: string
        required: true
        default: "https://api.skedulo.com"
      SOURCE_TOKEN:
        description: "Source API Token"
        type: string
        required: true
      TARGET_API_SERVER:
        description: "Target API server"
        type: string
        required: true
        default: "https://api.skedulo.com"
      TARGET_TOKEN:
        description: "Target API Token"
        type: string
        required: true
jobs:
  migration:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Migration
          uses: ./
          with:
            SOURCE_API_SERVER: ${{ github.event.inputs.SOURCE_API_SERVER }}
            SOURCE_TOKEN: ${{ github.event.inputs.SOURCE_TOKEN }}
            TARGET_API_SERVER: ${{ github.event.inputs.TARGET_API_SERVER }}
            TARGET_TOKEN: ${{ github.event.inputs.TARGET_TOKEN }}


